# DDP
gpus: "0,1,3"
flag: train

# Log
log_dir: "/home/chengxiaozhen/Test/ForensicHub/MyHub/log/crossdataset_convnextsmall_none_train"

# Task
if_predict_label: true
if_predict_mask: false

# Model
model:
  name: ConvNextSmall
  # Model specific setting
  init_config:
    output_type: label
    image_size: 256

# Train dataset
train_dataset:
  name: CrossDataset
  dataset_name: CrossDataset
  init_config:
    dataset_config:
      - name: LabelDataset
        pic_nums: 12641
        init_config:
          image_size: 256
          path: /home/censoring/data/train_data/FaceForensics++.json
      - name: LabelDataset
        pic_nums: 12641
        init_config:
          image_size: 256
          path:
            - /home/censoring/data/train_data/GenImage_ADM.json
            - /home/censoring/data/train_data/GenImage_BigGAN.json
            - /home/censoring/data/train_data/GenImage_glide.json
            - /home/censoring/data/train_data/GenImage_Midjourney.json
            - /home/censoring/data/train_data/GenImage_stable_diffusion_v_1_4.json
            - /home/censoring/data/train_data/GenImage_stable_diffusion_v_1_5.json
            - /home/censoring/data/train_data/GenImage_VQDM.json
            - /home/censoring/data/train_data/GenImage_wukong.json
      - name: LabelDataset
        pic_nums: 12641
        init_config:
          image_size: 256
          path: /home/censoring/data/train_data/CASIAv2.json
          #config_file: /mnt/data1/public_datasets/Deepfake/FaceForensics++.json

#  Test dataset (one or many)
test_dataset:
  - name: LabelDataset
    dataset_name: FF++_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/FaceForensics++.json
      # Dataset specific setting
      is_resizing: true
      is_padding: false
  - name: LabelDataset
    dataset_name: UADFV_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/UADFV_test.json
      # Dataset specific setting
      is_resizing: true
      is_padding: false
  - name: LabelDataset
    dataset_name: Celeb_DF_v1_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/Celeb-DF-v1_test.json
  - name: LabelDataset
    dataset_name: DFDC_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/DFDC_test.json
  - name: LabelDataset
    dataset_name: DFDCP_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/DFDCP_test.json
  - name: LabelDataset
    dataset_name: Celeb_DF_v2_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/Celeb-DF-v2_test.json
  - name: LabelDataset
    dataset_name: GenImage_ADM_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/GenImage_ADM.json
  - name: LabelDataset
    dataset_name: GenImage_BigGAN_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/GenImage_BigGAN.json
  - name: LabelDataset
    dataset_name: GenImage_glide_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/GenImage_glide.json
  - name: LabelDataset
    dataset_name: GenImage_Midjourney_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/GenImage_Midjourney.json
  - name: LabelDataset
    dataset_name: GenImage_stable_diffusion_v_1_4_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/GenImage_stable_diffusion_v_1_4.json
  - name: LabelDataset
    dataset_name: GenImage_stable_diffusion_v_1_5_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/GenImage_stable_diffusion_v_1_5.json
  - name: LabelDataset
    dataset_name: GenImage_VQDM_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/GenImage_VQDM.json
  - name: LabelDataset
    dataset_name: GenImage_wukong_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/GenImage_wukong.json
  - name: LabelDataset
    dataset_name: GenImage_SD_inpaint_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/SD_inpaint_test.json
  - name: LabelDataset
    dataset_name: Columbia_test
    init_config:
      image_size: 256
      path: /home/censoring/data/test_data/columbia.json
      #config_file: /mnt/data1/public_datasets/Deepfake/FF-DF.json
      #split_mode: test

# Transform
transform:
  name: CrossTransform

# Evaluators
evaluator:
  - name: ImageAccuracy
    init_config:
      threshold: 0.5

# Training related
batch_size: 128
test_batch_size: 128
epochs: 20
accum_iter: 1
record_epoch: 0  # Save the best only after record epoch.

# Test related
no_model_eval: false
test_period: 1

# Logging & TensorBoard
log_per_epoch_count: 20

# DDP & AMP settings
find_unused_parameters: true
use_amp: false

# Optimizer parameters
weight_decay: 0.05
lr: 1e-4
blr: 0.001
min_lr: 1e-5
warmup_epochs: 1

# Device and training control
device: "cuda"
seed: 42
resume: ""
start_epoch: 0
num_workers: 8
pin_mem: true

# Distributed training parameters
world_size: 1
local_rank: -1
dist_on_itp: false
dist_url: "env://"

